/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <nvrtc.h>
/* Header for class jcuda_driver_JNvrtc */

#ifndef _Included_jcuda_driver_JNvrtc
#define _Included_jcuda_driver_JNvrtc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jcuda_driver_JNvrtc
 * Method:    nvrtcCompileProgramNative
 * Signature: (Ljcuda/driver/CUprogram;I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_driver_JNvrtc_nvrtcCompileProgramNative
  (JNIEnv *, jclass, jobject, jint, jobjectArray);

/*
 * Class:     jcuda_driver_JNvrtc
 * Method:    nvrtcCreateProgramNative
 * Signature: (Ljcuda/driver/CUprogram;Ljava/lang/String;Ljava/lang/String;I[Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_driver_JNvrtc_nvrtcCreateProgramNative
  (JNIEnv *, jclass, jobject, jstring, jstring, jint, jobjectArray, jobjectArray);

/*
 * Class:     jcuda_driver_JNvrtc
 * Method:    nvrtcDestroyProgramNative
 * Signature: (Ljcuda/driver/CUprogram;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_driver_JNvrtc_nvrtcDestroyProgramNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_driver_JNvrtc
 * Method:    nvrtcGetPTXNative
 * Signature: (Ljcuda/driver/CUprogram;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_driver_JNvrtc_nvrtcGetPTXNative
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     jcuda_driver_JNvrtc
 * Method:    nvrtcGetPTXSizeNative
 * Signature: (Ljcuda/driver/CUprogram;[J)I
 */
JNIEXPORT jint JNICALL Java_jcuda_driver_JNvrtc_nvrtcGetPTXSizeNative
  (JNIEnv *, jclass, jobject, jlongArray);

/*
 * Class:     jcuda_driver_JNvrtc
 * Method:    nvrtcGetProgramLogNative
 * Signature: (Ljcuda/driver/CUprogram;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_driver_JNvrtc_nvrtcGetProgramLogNative
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     jcuda_driver_JNvrtc
 * Method:    nvrtcGetProgramLogSizeNative
 * Signature: (Ljcuda/driver/CUprogram;[J)I
 */
JNIEXPORT jint JNICALL Java_jcuda_driver_JNvrtc_nvrtcGetProgramLogSizeNative
  (JNIEnv *, jclass, jobject, jlongArray);


JNIEXPORT jint JNICALL Java_jcuda_driver_JNvrtc_cuModuleLoadDataExNative
(JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
